name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR Diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt

      - name: Show Debug Info (optional)
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          head -n 20 pr_diff.txt

      - name: Send Diff to AI Review Bot
        run: |
          DIFF_CONTENT=$(cat pr_diff.txt | jq -Rs .)
          jq -n \
            --arg repo "${{ github.repository }}" \
            --argjson pr_number ${{ github.event.pull_request.number }} \
            --arg diff "$DIFF_CONTENT" \
            '{repo_full_name: $repo, pr_number: $pr_number, diff: $diff}' \
          | curl -X POST https://ai-based-pr-review.onrender.com/review \
              -H "Content-Type: application/json" \
              -d @-
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
